#include <stdlib.h>
#include <time.h>
#include <random>
#include <iostream>

using namespace std;

/*void dissemble_op(unsigned char opcode){
    switch(opcode){
        case 0x0:cout<<"NOP"<<endl; break;
        case 0x1:cout<<"LXI B "<<"d16"<<endl; break;
        case 0x2:cout<<"STAX B "<<endl; break;
        case 0x3:cout<<"inc16 B "<<endl; break;
        case 0x4:cout<<"inc B "<<endl; break;
        case 0x5:cout<<"dec B "<<endl; break;
        case 0x6:cout<<"MVI B "<<"d8"<<endl; break;
        case 0x7:cout<<"rlca "<<endl; break;
        case 0x8:cout<<"EX AF,AF'"<<endl; break;
        case 0x9:cout<<"DAD B"<<endl; break;
        case 0xa:cout<<"LDAX B "<<endl; break;
        case 0xb:cout<<"DCX B "<<endl; break;
        case 0xc:cout<<"inc C "<<endl; break;
        case 0xd:cout<<"DCR C "<<endl; break;
        case 0xe:cout<<"MVI C "<<"d8"<<endl; break;
        case 0xf:cout<<"RRC A "<<endl; break;
        case 0x10:cout<<"*djnz"<<endl; break;
        case 0x11:cout<<"LXI D "<<"d16"<<endl; break;
        case 0x12:cout<<"STAX D "<<endl; break;
        case 0x13:cout<<"inc16 D "<<endl; break;
        case 0x14:cout<<"inc D "<<endl; break;
        case 0x15:cout<<"DCR D "<<endl; break;
        case 0x16:cout<<"MVI D "<<"d8"<<endl; break;
        case 0x17:cout<<"RAL  "<<endl; break;
        case 0x18:cout<<"Jr d8"<<endl; break;
        case 0x19:cout<<"DAD D"<<endl; break;
        case 0x1a:cout<<"LDAX D "<<endl; break;
        case 0x1b:cout<<"DCX D "<<endl; break;
        case 0x1c:cout<<"inc E "<<endl; break;
        case 0x1d:cout<<"DCR E "<<endl; break;
        case 0x1e:cout<<"MVI E "<<"d8"<<endl; break;
        case 0x1f:cout<<"RAR "<<endl; break;
        case 0x20:cout<<"Jr nz d8"<<endl; break;
        case 0x21:cout<<"LXI H "<<"d16"<<endl; break;
        case 0x22:cout<<"SHLD "<<"d16"<<endl; break;
        case 0x23:cout<<"inc16 H "<<endl; break;
        case 0x24:cout<<"inc H "<<endl; break;
        case 0x25:cout<<"DCR H "<<endl; break;
        case 0x26:cout<<"MVI H "<<"d8"<<endl; break;
        case 0x27:cout<<"Daa"<<endl; break;
        case 0x28:cout<<"Jr Z d8"<<endl; break;
        case 0x29:cout<<"DAD H"<<endl; break;
        case 0x2a:cout<<"LHLD "<<"d16"<<endl; break;
        case 0x2b:cout<<"DCX H "<<endl; break;
        case 0x2c:cout<<"inc L "<<endl; break;
        case 0x2d:cout<<"DCR L "<<endl; break;
        case 0x2e:cout<<"MVI L "<<"d8"<<endl; break;
        case 0x2f:cout<<"cpl"<<endl; break;
        case 0x30:cout<<"Jr NC d8"<<endl; break;
        case 0x31:cout<<"Lxi SP "<<"d16"<<endl; break;
        case 0x32:cout<<"STA "<<"d16"<<endl; break;
        case 0x33:cout<<"inc16 SP "<<endl; break;
        case 0x34:cout<<"inc M "<<endl; break;
        case 0x35:cout<<"DCR M "<<endl; break;
        case 0x36:cout<<"MVI M "<<"d8"<<endl; break;
        case 0x37:cout<<"scf"<<endl; break;
        case 0x38:cout<<"Jr C d8"<<endl; break;
        case 0x39:cout<<"DAD SP"<<endl; break;
        case 0x3a:cout<<"LDA "<<"d16"<<endl; break;
        case 0x3b:cout<<"DCX SP "<<endl; break;
        case 0x3c:cout<<"inc A "<<endl; break;
        case 0x3d:cout<<"DCR A "<<endl; break;
        case 0x3e:cout<<"MVI A "<<"d8"<<endl; break;
        case 0x3f:cout<<"ccf"<<endl; break;
        case 0x40:cout<<"ld B,B "<<endl; break;
        case 0x41:cout<<"ld B,C "<<endl; break;
        case 0x42:cout<<"ld B,D "<<endl; break;
        case 0x43:cout<<"ld B,E "<<endl; break;
        case 0x44:cout<<"ld B,H "<<endl; break;
        case 0x45:cout<<"ld B,L "<<endl; break;
        case 0x46:cout<<"ld B,M "<<endl; break;
        case 0x47:cout<<"ld B,A "<<endl; break;
        case 0x48:cout<<"ld C,B "<<endl; break;
        case 0x49:cout<<"ld C,C "<<endl; break;
        case 0x4a:cout<<"ld C,D "<<endl; break;
        case 0x4b:cout<<"ld C,E "<<endl; break;
        case 0x4c:cout<<"ld C,H "<<endl; break;
        case 0x4d:cout<<"ld C,L "<<endl; break;
        case 0x4e:cout<<"ld C,M "<<endl; break;
        case 0x4f:cout<<"ld C,A "<<endl; break;
        case 0x50:cout<<"ld D,B "<<endl; break;
        case 0x51:cout<<"ld D,B "<<endl; break;
        case 0x52:cout<<"ld D,D "<<endl; break;
        case 0x53:cout<<"ld D,E "<<endl; break;
        case 0x54:cout<<"ld D,H "<<endl; break;
        case 0x55:cout<<"ld D,L "<<endl; break;
        case 0x56:cout<<"ld D,M "<<endl; break;
        case 0x57:cout<<"ld D,A "<<endl; break;
        case 0x58:cout<<"ld E,B "<<endl; break;
        case 0x59:cout<<"ld E,C "<<endl; break;
        case 0x5a:cout<<"ld E,D "<<endl; break;
        case 0x5b:cout<<"ld E,E "<<endl; break;
        case 0x5c:cout<<"ld E,H "<<endl; break;
        case 0x5d:cout<<"ld E,L "<<endl; break;
        case 0x5e:cout<<"ld E,M "<<endl; break;
        case 0x5f:cout<<"ld E,A "<<endl; break;
        case 0x60:cout<<"ld H,B "<<endl; break;
        case 0x61:cout<<"ld H,B "<<endl; break;
        case 0x62:cout<<"ld H,D "<<endl; break;
        case 0x63:cout<<"ld H,E "<<endl; break;
        case 0x64:cout<<"ld H,H "<<endl; break;
        case 0x65:cout<<"ld H,L "<<endl; break;
        case 0x66:cout<<"ld H,M "<<endl; break;
        case 0x67:cout<<"ld H,A "<<endl; break;
        case 0x68:cout<<"ld L,B "<<endl; break;
        case 0x69:cout<<"ld L,C "<<endl; break;
        case 0x6a:cout<<"ld L,D "<<endl; break;
        case 0x6b:cout<<"ld L,E "<<endl; break;
        case 0x6c:cout<<"ld L,H "<<endl; break;
        case 0x6d:cout<<"ld L,L "<<endl; break;
        case 0x6e:cout<<"ld L,M "<<endl; break;
        case 0x6f:cout<<"ld L,A "<<endl; break;
        case 0x70:cout<<"ld M,B "<<endl; break;
        case 0x71:cout<<"ld M,B "<<endl; break;
        case 0x72:cout<<"ld M,D "<<endl; break;
        case 0x73:cout<<"ld M,E "<<endl; break;
        case 0x74:cout<<"ld M,H "<<endl; break;
        case 0x75:cout<<"ld M,L "<<endl; break;
        case 0x76:cout<<"Halt "<<endl; break;
        case 0x77:cout<<"ld M,A "<<endl; break;
        case 0x78:cout<<"ld A,B "<<endl; break;
        case 0x79:cout<<"ld A,C "<<endl; break;
        case 0x7a:cout<<"ld A,D "<<endl; break;
        case 0x7b:cout<<"ld A,E "<<endl; break;
        case 0x7c:cout<<"ld A,H "<<endl; break;
        case 0x7d:cout<<"ld A,L "<<endl; break;
        case 0x7e:cout<<"ld A,M "<<endl; break;
        case 0x7f:cout<<"ld A,A "<<endl; break;
        case 0x80:cout<<"ADD A B "<<endl; break;
        case 0x81:cout<<"ADD A C "<<endl; break;
        case 0x82:cout<<"ADD A D "<<endl; break;
        case 0x83:cout<<"ADD A E "<<endl; break;
        case 0x84:cout<<"ADD A H "<<endl; break;
        case 0x85:cout<<"ADD A L "<<endl; break;
        case 0x86:cout<<"ADD A M "<<endl; break;
        case 0x87:cout<<"ADD A A "<<endl; break;
        case 0x88:cout<<"ADC A B "<<endl; break;
        case 0x89:cout<<"ADC A C "<<endl; break;
        case 0x8a:cout<<"ADC A D "<<endl; break;
        case 0x8b:cout<<"ADC A E "<<endl; break;
        case 0x8c:cout<<"ADC A H "<<endl; break;
        case 0x8d:cout<<"ADC A L "<<endl; break;
        case 0x8e:cout<<"ADC A M "<<endl; break;
        case 0x8f:cout<<"ADC A A "<<endl; break;
        case 0x90:cout<<"SUB A B "<<endl; break;
        case 0x91:cout<<"SUB A C "<<endl; break;
        case 0x92:cout<<"SUB A D "<<endl; break;
        case 0x93:cout<<"SUB A E "<<endl; break;
        case 0x94:cout<<"SUB A H "<<endl; break;
        case 0x95:cout<<"SUB A L "<<endl; break;
        case 0x96:cout<<"SUB A M "<<endl; break;
        case 0x97:cout<<"SUB A A "<<endl; break;
        case 0x98:cout<<"sbc A B "<<endl; break;
        case 0x99:cout<<"sbc A C "<<endl; break;
        case 0x9a:cout<<"sbc A D "<<endl; break;
        case 0x9b:cout<<"sbc A E "<<endl; break;
        case 0x9c:cout<<"sbc A H "<<endl; break;
        case 0x9d:cout<<"sbc A L "<<endl; break;
        case 0x9e:cout<<"sbc A M "<<endl; break;
        case 0x9f:cout<<"sbc A A "<<endl; break;
        case 0xa0:cout<<"ANA A B "<<endl; break;
        case 0xa1:cout<<"ANA A C "<<endl; break;
        case 0xa2:cout<<"ANA A D "<<endl; break;
        case 0xa3:cout<<"ANA A E "<<endl; break;
        case 0xa4:cout<<"ANA A H "<<endl; break;
        case 0xa5:cout<<"ANA A L "<<endl; break;
        case 0xa6:cout<<"ANA A M "<<endl; break;
        case 0xa7:cout<<"ANA A A "<<endl; break;
        case 0xa8:cout<<"XRA A B "<<endl; break;
        case 0xa9:cout<<"XRA A C "<<endl; break;
        case 0xaa:cout<<"XRA A D "<<endl; break;
        case 0xab:cout<<"XRA A E "<<endl; break;
        case 0xac:cout<<"XRA A H "<<endl; break;
        case 0xad:cout<<"XRA A L "<<endl; break;
        case 0xae:cout<<"XRA A M "<<endl; break;
        case 0xaf:cout<<"XRA A A "<<endl; break;
        case 0xb0:cout<<"ORA A B "<<endl; break;
        case 0xb1:cout<<"ORA A C "<<endl; break;
        case 0xb2:cout<<"ORA A D "<<endl; break;
        case 0xb3:cout<<"ORA A E "<<endl; break;
        case 0xb4:cout<<"ORA A H "<<endl; break;
        case 0xb5:cout<<"ORA A L "<<endl; break;
        case 0xb6:cout<<"ORA A M "<<endl; break;
        case 0xb7:cout<<"ORA A A "<<endl; break;
        case 0xb8:cout<<"CMP A B "<<endl; break;
        case 0xb9:cout<<"CMP A C "<<endl; break;
        case 0xba:cout<<"CMP A D "<<endl; break;
        case 0xbb:cout<<"CMP A E "<<endl; break;
        case 0xbc:cout<<"CMP A H "<<endl; break;
        case 0xbd:cout<<"CMP A L "<<endl; break;
        case 0xbe:cout<<"CMP A M "<<endl; break;
        case 0xbf:cout<<"CMP A A "<<endl; break;
        case 0xc0:cout<<"RNZ "<<endl; break;
        case 0xc1:cout<<"POP B "<<endl; break;
        case 0xc2:cout<<"JNZ "<<"d16"<<endl; break;
        case 0xc3:cout<<"JMP "<<"d16"<<endl; break;
        case 0xc4:cout<<"CNZ "<<"d16"<<endl; break;
        case 0xc5:cout<<"PUSH B "<<endl; break;
        case 0xc6:cout<<"ADI A "<<"d8"<<endl; break;
        case 0xc7:cout<<"Rst 0"<<endl; break;
        case 0xc8:cout<<"RZ "<<endl; break;
        case 0xc9:cout<<"Ret "<<endl; break;
        case 0xca:cout<<"JZ "<<"d16"<<endl; break;
        case 0xcb:cout<<"Bit instruction ";
        case 0xcc:cout<<"CZ "<<"d16"<<endl; break;
        case 0xcd:cout<<"CALL "<<"d16"<<endl; break;
        case 0xce:cout<<"ACI A "<<"d8"<<endl; break;
        case 0xcf:cout<<"Rst 8"<<endl; break;
        case 0xd0:cout<<"RNC "<<endl; break;
        case 0xd1:cout<<"POP D "<<endl; break;
        case 0xd2:cout<<"JNC "<<"d16"<<endl; break;
        case 0xd3:cout<<"OUT (later)"<<"d8"<<endl; break;
        case 0xd4:cout<<"CNC "<<"d16"<<endl; break;
        case 0xd5:cout<<"PUSH D "<<endl; break;
        case 0xd6:cout<<"SUI A "<<"d8"<<endl; break;
        case 0xd7:cout<<"Rst 10"<<endl; break;
        case 0xd8:cout<<"RC "<<endl; break;
        case 0xd9:cout<<"EXX"<<endl; break;
        case 0xda:cout<<"JC "<<"d16"<<endl; break;
        case 0xdb:cout<<"IN (later) "<<"d8"<<endl; break;
        case 0xdc:cout<<"CC "<<"d16"<<endl; break;
        case 0xdd:cout<<"IX instruction ";
        case 0xde:cout<<"SBI A "<<"d8"<<endl; break;
        case 0xdf:cout<<"Rst 18"<<endl; break;
        case 0xe0:cout<<"RPO "<<endl; break;
        case 0xe1:cout<<"POP H "<<endl; break;
        case 0xe2:cout<<"JPO "<<"d16"<<endl; break;
        case 0xe3:cout<<"XTHL "<<endl; break;
        case 0xe4:cout<<"CPO "<<"d16"<<endl; break;
        case 0xe5:cout<<"PUSH H "<<endl; break;
        case 0xe6:cout<<"ANI A "<<"d8"<<endl; break;
        case 0xe7:cout<<"Rst 20"<<endl; break;
        case 0xe8:cout<<"RPE "<<endl; break;
        case 0xe9:cout<<"PCHL "<<endl; break;
        case 0xea:cout<<"JPE "<<"d16"<<endl; break;
        case 0xeb:cout<<"XCHG "<<endl; break;
        case 0xec:cout<<"CPE "<<"d16"<<endl; break;
        case 0xed:cout<<"Extended instruction ";
        case 0xee:cout<<"XRI A "<<"d8"<<endl; break;
        case 0xef:cout<<"Rst 28"<<endl; break;
        case 0xf0:cout<<"RNZ "<<endl; break;
        case 0xf1:cout<<"POP PSW "<<endl; break;
        case 0xf2:cout<<"JP "<<"d16"<<endl; break;
        case 0xf3:cout<<"DI "<<endl; break;
        case 0xf4:cout<<"CP "<<"d16"<<endl; break;
        case 0xf5:cout<<"PUSH PSW "<<endl; break;
        case 0xf6:cout<<"ORA A "<<"d8"<<endl; break;
        case 0xf7:cout<<"Rst 30"<<endl; break;
        case 0xf8:cout<<"RNZ "<<endl; break;
        case 0xf9:cout<<"SPHL "<<endl; break;
        case 0xfa:cout<<"JM "<<"d16"<<endl; break;
        case 0xfb:cout<<"EI "<<endl; break;
        case 0xfc:cout<<"CM "<<"d16"<<endl; break;
        case 0xfd:cout<<"IY instruction ";
        case 0xfe:cout<<"CPI "<<"d8"<<endl; break;
        case 0xff:cout<<"Rst 38"<<endl; break;
    }
}*/